// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQ3wpeeFCKORWpvJC3mrX2JFq0pzAmTo',
    appId: '1:85488518417:web:4a405709f39614a725b8b0',
    messagingSenderId: '85488518417',
    projectId: 'servicehub-provider',
    authDomain: 'servicehub-provider.firebaseapp.com',
    storageBucket: 'servicehub-provider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwuXBO3PPsyG3pweFms7fSRsDfpomf7U',
    appId: '1:85488518417:android:713fa2154502f30d25b8b0',
    messagingSenderId: '85488518417',
    projectId: 'servicehub-provider',
    storageBucket: 'servicehub-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSVd96ktzA3Y9k5ubquJ9xtz8FJWsQSM',
    appId: '1:85488518417:ios:4af09f2507feded625b8b0',
    messagingSenderId: '85488518417',
    projectId: 'servicehub-provider',
    storageBucket: 'servicehub-provider.appspot.com',
    androidClientId: '85488518417-bjhg0827fauhggu54lb6tmbgnk9m241u.apps.googleusercontent.com',
    iosClientId: '85488518417-ffs5av82u4of20bl3vutujnsg1eqmj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSVd96ktzA3Y9k5ubquJ9xtz8FJWsQSM',
    appId: '1:85488518417:ios:4af09f2507feded625b8b0',
    messagingSenderId: '85488518417',
    projectId: 'servicehub-provider',
    storageBucket: 'servicehub-provider.appspot.com',
    androidClientId: '85488518417-bjhg0827fauhggu54lb6tmbgnk9m241u.apps.googleusercontent.com',
    iosClientId: '85488518417-ffs5av82u4of20bl3vutujnsg1eqmj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicehub',
  );
}
